// <auto-generated />
namespace DBSP.RememberMe.API.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedScheduleTimeForNote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedScheduleTimeForNote));
        
        string IMigrationMetadata.Id
        {
            get { return "201609121941359_AddedScheduleTimeForNote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
